# Generated by Django 5.2.12 on 2026-03-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='stat_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='stat_value',
            field=models.FloatField(default=0.0),
        ),
    ]
