# Generated by Django 5.2.12 on 2026-03-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_stats_stat_rank_alter_stats_stat_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Healer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healer_title', models.CharField(max_length=100)),
                ('healer_stats', models.ManyToManyField(related_name='healer_stats', to='main_app.stats')),
            ],
        ),
    ]
