# Generated by Django 5.2.12 on 2026-03-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_stats_stat_rank_alter_stats_stat_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=100)),
                ('weapon_type', models.CharField(max_length=100)),
            ],
        ),
    ]
