# Generated by Django 5.2.12 on 2026-03-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_weapons'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dps_title', models.CharField(max_length=100)),
                ('dps_stats', models.ManyToManyField(related_name='dps_stats', to='main_app.stats')),
                ('dps_weapon', models.ManyToManyField(related_name='dps_weapon', to='main_app.weapons')),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_title', models.CharField(max_length=100)),
                ('tank_stats', models.ManyToManyField(related_name='tank_stats', to='main_app.stats')),
                ('tank_weapon', models.ManyToManyField(related_name='tank_weapon', to='main_app.weapons')),
            ],
        ),
    ]
