# Generated by Django 5.2.12 on 2026-03-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_healer'),
        ('main_app', '0004_dps_tank'),
    ]

    operations = [
    ]
